// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCofKCYlJxGaU2rb6enDkr6JeB84IbIsQk',
    appId: '1:256797069150:web:214fd884afb2ef533e09cf',
    messagingSenderId: '256797069150',
    projectId: 'music-player-ba9fe',
    authDomain: 'music-player-ba9fe.firebaseapp.com',
    storageBucket: 'music-player-ba9fe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9osd6-Tmo7ImgaEpwZTteQy2tctGOLwE',
    appId: '1:256797069150:android:5cff2e6c7c4907a03e09cf',
    messagingSenderId: '256797069150',
    projectId: 'music-player-ba9fe',
    storageBucket: 'music-player-ba9fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLcfkoUZ3gqYMXZNP37b2zJBR7udnjCTQ',
    appId: '1:256797069150:ios:7ad8354ee6f0bb973e09cf',
    messagingSenderId: '256797069150',
    projectId: 'music-player-ba9fe',
    storageBucket: 'music-player-ba9fe.appspot.com',
    iosClientId: '256797069150-erstpdqsv3salr4a9qeq8sd27vmqo1kt.apps.googleusercontent.com',
    iosBundleId: 'com.example.myMusic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLcfkoUZ3gqYMXZNP37b2zJBR7udnjCTQ',
    appId: '1:256797069150:ios:1811838380f61d4f3e09cf',
    messagingSenderId: '256797069150',
    projectId: 'music-player-ba9fe',
    storageBucket: 'music-player-ba9fe.appspot.com',
    iosClientId: '256797069150-5e7u4he8dd1gv4pv20geuk8e6i68ki58.apps.googleusercontent.com',
    iosBundleId: 'com.example.myMusic.RunnerTests',
  );
}
